Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-private-repo
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
          - Sid: AllowPull
            Effect: Allow
            Principal: '*'
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Sub "arn:aws:iam::${AWS::AccountId}:root"
